#!/bin/sh
set -e

lb config noauto \
	--architectures "i386" \
	--linux-flavours "686" \
	--archive-areas "main contrib non-free" \
	--bootappend-live "boot=live config persistence username=mame hostname=live-mame" \
	--memtest "memtest86+" \
	--iso-application "Live MAME" \
	--iso-volume "Live MAME" \
	--iso-preparer "Chris Landa <chris@1337.af>" \
	--iso-publisher "Chris Landa <chris@1337.af>" \
	"${@}"
